# Generated by Django 2.2.16 on 2023-04-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230414_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('superuser', 'superuser'), ('admin', 'admin')], default='user', max_length=9),
        ),
    ]
